name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up PHP and install dependencies via Composer
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Specify the PHP version you're using

      # Step 3: Install PHP dependencies using Composer
      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-interaction

      # Step 4: Set up Node.js (if you also have npm dependencies)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you're using

      # Step 5: Install Node.js dependencies (if applicable)
      - name: Install npm dependencies
        run: npm install

      # Step 6: Run tests (for PHPUnit or any other testing tool you use)
      - name: Run PHP tests
        run: vendor\bin\phpunit

      # Step 7: Optionally build the project if needed
      - name: Build the project (optional)
        run: npm run build

      # Step 8: Deploy (if needed)
      - name: Deploy
        run: |
          echo "Deploying project..."
