name: PHP CI with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        coverage: xdebug # Enables coverage with Xdebug

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Run PHPUnit with Coverage
      run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        fail_ci_if_error: true

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --level=max
