name: PHP CI with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug # Enable Xdebug for code coverage

      # Install dependencies
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      # Run tests and generate coverage
      - name: Run PHPUnit tests
        run: |
          mkdir -p build/coverage
          vendor/bin/phpunit --coverage-clover build/coverage/clover.xml

      # Upload code coverage to Codecov (Optional)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: build/coverage/clover.xml
          fail_ci_if_error: true

      # (Optional) Save coverage report as an artifact
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/coverage/
