name: Core PHP CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, mysql

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Run Static Analysis
      run: vendor/bin/phpstan analyse

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --coverage-text
